INSERT INTO PRODUTO (NOME, PRECO) VALUES ('Notebook Dell', 3899.99);
INSERT INTO PRODUTO (NOME, PRECO) VALUES ('Monitor 24 polegadas', 899.90);
INSERT INTO PRODUTO (NOME, PRECO) VALUES ('Teclado mecânico', 299.90);
INSERT INTO PRODUTO (NOME, PRECO) VALUES ('Mouse gamer', 159.90);
